### ISSUE TITLE
Computation of derivative

### ISSUE THREAD

**Issue by LeiYangJustin** [matanatz/SALD#1]
Hi, I want to know how you prepare the derivative data for training supervision. In the paper, it says the derivative at x' is chosen from two of the possible normal vectors +/- n (A.2.2). However, there is no other information about how the normal vector is computed. I am wondering if the given data is a point set (not triangle soup), then do you use the local neighborhood to compute the normal vectors?

**Comment by matanatz** [comment]
please see,
https://github.com/matanatz/SALD/blob/bfc4768a0a783a4a6d2424d9ceedd3d64342fd2d/code/preprocess/preprocess_dfaust.py#L126
